routes/web.php
<?php

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/app', function () {
    return view('Layout.index');
})->middleware('auth')->name('dashboard');
Route::get('/test', function () {
    return view('test.index');
});

Route::post('/login',[\App\Http\Controllers\LoginController::class, 'login'])->name('login');

Route::get('/logout',[\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

Route::resource('users', UserController::class);
Route::resource('roles', RoleController::class);

Route::get('/login', function () {
    return view('login');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all = User::all();
        return view('users.index',['users' => $all]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        

        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
       
        $user = new User;
        
        $user->username = $request->username;
        
        $user->name = $request->fname." ".$request->lname;
        
        $user->email = $request->email;
        
        $user->contact_number = $request->contact_number;
        $user->posation = $request->posation;
        $user->status = "1";
        $user->password = Hash::make('Afghan@786');
        $user->save();
        
        $user->syncRoles($request['role']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return "show <br>".$user;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return "edit <br>".$user;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $delete_user = User::find($user->id);
        $delete_user->delete();

        return redirect()->route('users.index')->with('message', __('general.record_deleted'));
    }
}

resources/views/users/create.blade.php
@extends('Layout.index')


@section('content')
<!-- Content area -->

<div class="content d-flex justify-content-center align-items-center">

    <!-- Registration form -->
    <form action="{{route('users.store')}}" class="flex-fill" method="POST">
        @csrf
        <div class="row">
            <div class="col-lg-12">
                <div class="card mb-0">
                    <div class="card-body">
                        <div class="text-center mb-3">
                            <i class="icon-plus3 icon-2x text-success border-success border-3 rounded-round p-3 mb-3 mt-1"></i>
                            <h5 class="mb-0">Create account</h5>
                            <span class="d-block text-muted">All fields are required</span>
                        </div>

                        <div class="form-group form-group-feedback form-group-feedback-right">
                            <input type="text" class="form-control" placeholder="Choose username" name="username">
                            <div class="form-control-feedback">
                                <i class="icon-user-plus text-muted"></i>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <input type="text" class="form-control" placeholder="First name" name="fname">
                                    <div class="form-control-feedback">
                                        <i class="icon-user-check text-muted"></i>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <input type="text" class="form-control" placeholder="Second name" name="lname">
                                    <div class="form-control-feedback">
                                        <i class="icon-user-check text-muted"></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                      

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <input type="email" class="form-control" placeholder="Your email" name="email">
                                    <div class="form-control-feedback">
                                        <i class="icon-mention text-muted"></i>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <div class="input-group">
                                        <span class="input-group-prepend">
                                            <span class="input-group-text">+93</span>
                                        </span>
                                        <input type="text" class="form-control" placeholder="Contact Number" name="contact_number">
                                    </div>
                                
                                    
                                    <div class="form-control-feedback">
                                        <i class="icon-phone2 text-muted"></i>
                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                        </div>
                        <div class="form-group form-group-feedback form-group-feedback-right">
                            <input type="text" class="form-control" placeholder="job title/posation" name="posation">
                            <div class="form-control-feedback">
                                <i class="icon-user-plus text-muted"></i>
                            </div>
                        </div>
                        
                        
                
                        <div class="form-group col-sm-5">
                            <label></label>
                            <select data-placeholder="Select User Role" class="form-control select" name="role" data-fouc>
                                <option></option>
                                <optgroup>
                                    @foreach ($roles as $role)
                                    <option value="{{$role->id}}">{{$role->name}}</option> 
                                    @endforeach
                                </optgroup>
                            </select>
                        </div>

                        <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right"><b><i class="icon-plus3"></i></b> Create account</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- /registration form -->

</div>
<!-- /content area -->

@endsection

resources/views/users/index.blade.php
@extends('Layout.index')

@section('content')



	<!-- Basic initialization
    
   
    -->
    <div class="card">
      

        <div class="card-header header-elements-inline">
            <h5 class="card-title">Basic initialization</h5>
            <div class="header-elements">
            
            </div>
        </div>

        <div class="card-body">
            The HTML5 export buttons plug-in for Buttons provides four export buttons: <code>copyHtml5</code> - copy to clipboard; <code>csvHtml5</code> - save to CSV file; <code>excelHtml5</code> - save to XLSX file (requires JSZip); <code>pdfHtml5</code> - save to PDF file (requires PDFMake). This example demonstrates these four button types with their default options. Please note that these button types may also use a Flash fallback for older browsers (IE9-).
        </div>					
        <table class="table datatable-button-html5-basic">

            <thead>
                <tr>
                    <th>Username</th>
                    <th>Email </th>
                    <th>Role</th>
                    <th>status</th>
                    <th>Posation</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                <tr>
                    <td>{{$user->username;}}</td>
                    <td><a href="#">{{$user->email;}}</a></td>
                    <td>  @foreach($user->getRoleNames() as $role)
                        {{ $role }}
                      @endforeach</td>
                    <td>@if ($user->status == 1)
                        <span class="badge badge-success">Active</span>
                   
                            
                        @else
                        <span class="badge badge-success bg-danger">inActive</span>  
                        @endif
                    </td>
                    <td>{{$user->posation;}}</td>
                    <td>
                        <div class="list-icons">
         
                            <a href="{{ route('users.show', $user->id)}}" class="list-icons-item text-teal-600"><i class="icon-eye8"></i></a>
                            <a href="{{ route('users.edit', $user->id)}}" class="list-icons-item text-primary-600"><i class="icon-pencil7"></i></a>
                            
                            <a onclick="confirmDelete({{ $user->id }})" href="#" class="list-icons-item text-danger-600"><i class="icon-trash"></i></a>
                          

                            <form id="delete{{$user->id}}" action="{{ route('users.destroy', $user->id)}}" method="post">
                              @csrf
                              @method('DELETE')
                            </form>
                        </div>
                    </td>
                </tr>
                @endforeach
             
             
            </tbody>
        </table>
    </div>
    
<script>
    function confirmDelete(id) {
      let text = 'آیا مطمین استید تا این ریکارد حذف شود؟';
      if (confirm(text) == true) {
        $('form#delete'+id).submit();
    
      } else {
        alert('ریکارد حذف نشد.');
      }
    
    }
    </script>
    
    <!-- /basic initialization -->

@endsection