routes/web.php
<?php

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/app', function () {
    return view('Layout.index');
})->middleware('auth')->name('dashboard');
Route::get('/test', function () {
    return view('test.index');
});

Route::post('/login',[\App\Http\Controllers\LoginController::class, 'login'])->name('login');

Route::get('/logout',[\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

Route::resource('users', UserController::class);
Route::resource('roles', RoleController::class);

Route::get('/login', function () {
    return view('login');
});

resources/views/Layout/footer.blade.php
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            Footer
        </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-footer">
        <span class="navbar-text">
            &copy; 2015 - 2018. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
        </span>

        <ul class="navbar-nav ml-lg-auto">
            <li class="nav-item"><a href="https://kopyov.ticksy.com/" class="navbar-nav-link" target="_blank"><i class="icon-lifebuoy mr-2"></i> Support</a></li>
            <li class="nav-item"><a href="http://demo.interface.club/limitless/docs/" class="navbar-nav-link" target="_blank"><i class="icon-file-text2 mr-2"></i> Docs</a></li>
            <li class="nav-item"><a href="https://themeforest.net/item/limitless-responsive-web-application-kit/13080328?ref=kopyov" class="navbar-nav-link font-weight-semibold"><span class="text-pink-400"><i class="icon-cart2 mr-2"></i> Purchase</span></a></li>
        </ul>
    </div>
</div>

resources/views/Layout/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>

		<!-- Global stylesheets -->
		<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
		<link href="{{asset('global_assets/css/icons/icomoon/styles.min.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('assets/css/bootstrap_limitless.min.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('assets/css/layout.min.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('assets/css/components.min.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('assets/css/colors.min.css')}}" rel="stylesheet" type="text/css">
		<!-- /global stylesheets -->
	
		<!-- Core JS files -->
		<script src="{{asset('global_assets/js/main/jquery.min.js')}}"></script>
		<script src="{{asset('global_assets/js/main/bootstrap.bundle.min.js')}}"></script>
		<script src="{{asset('global_assets/js/plugins/loaders/blockui.min.js')}}"></script>
		<!-- /core JS files -->
	
		<!-- Theme JS files -->
		<script src="{{asset('global_assets/js/plugins/tables/datatables/datatables.min.js')}}"></script>
		<script src="{{asset('global_assets/js/plugins/forms/selects/select2.min.js')}}"></script>
		<script src="{{asset('global_assets/js/plugins/tables/datatables/extensions/jszip/jszip.min.js')}}"></script>
		<script src="{{asset('global_assets/js/plugins/tables/datatables/extensions/pdfmake/pdfmake.min.js')}}"></script>
		<script src="{{asset('global_assets/js/plugins/tables/datatables/extensions/pdfmake/vfs_fonts.min.js')}}"></script>
		<script src="{{asset('global_assets/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
		<script src="{{asset('global_assets/js/demo_pages/form_select2.js')}}"></script>
		
	
		<script src="{{asset('assets/js/app.js')}}"></script>
		
	<script src="{{asset('global_assets/js/demo_pages/datatables_extension_buttons_print.js')}}"></script>
		<script src="{{asset('global_assets/js/demo_pages/datatables_extension_buttons_html5.js')}}"></script>
		<!-- /theme JS files -->

</head>

<body>

	<!-- Main navbar -->
	@include('Layout.header')
	<!-- /main navbar -->

					
	<!-- Page content -->
	<div class="page-content">

		<!-- Main sidebar -->
		@include('Layout.sidebar')
		<!-- /main sidebar -->


		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Page header -->
			<div class="page-header">
				<div class="page-header-content header-elements-md-inline">
					<div class="page-title d-flex">
						<h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Dashboard</h4>
						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div>

				<!--
						<div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
						<div class="btn-group">
							<button type="button" class="btn bg-indigo-400"><i class="icon-stack2 mr-2"></i> New report</button>
							<button type="button" class="btn bg-indigo-400 dropdown-toggle" data-toggle="dropdown"></button>
							<div class="dropdown-menu dropdown-menu-right">
								<div class="dropdown-header">Actions</div>
								<a href="#" class="dropdown-item"><i class="icon-file-eye"></i> View reports</a>
								<a href="#" class="dropdown-item"><i class="icon-file-plus"></i> Edit reports</a>
								<a href="#" class="dropdown-item"><i class="icon-file-stats"></i> Statistics</a>
								<div class="dropdown-header">Export</div>
								<a href="#" class="dropdown-item"><i class="icon-file-pdf"></i> Export to PDF</a>
								<a href="#" class="dropdown-item"><i class="icon-file-excel"></i> Export to CSV</a>
							</div>
						</div>
					</div>
				-->
				</div>
			</div>
			<!-- /page header -->


			<!-- Content area -->
			<div class="content pt-0">

				<!-- Main charts -->
				
				<!-- /main charts -->

					@yield('content')
				<!-- Dashboard content -->
			
				<!-- /dashboard content -->

			</div>
			<!-- /content area -->


			<!-- Footer -->
			@include('Layout.footer')
			<!-- /footer -->

		</div>
		<!-- /main content -->

	</div>
	<!-- /page content -->

</body>
</html>

resources/views/Layout/sidebar.blade.php
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->


    <!-- Sidebar content -->
    <div class="sidebar-content">
        
        <!-- User menu -->
        <div class="sidebar-user">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3">
                        <a href="#"><img src="global_assets/images/placeholders/placeholder.jpg" width="38" height="38" class="rounded-circle" alt=""></a>
                    </div>

                    <div class="media-body">
                        <div class="media-title font-weight-semibold">{{ session('name')}}</div>
                        <div class="font-size-xs opacity-50">
                            <i class="icon-envelop5 font-size-sm"></i> &nbsp;{{ session('email')}}
                        </div>
                    </div>

                    <div class="ml-3 align-self-center">
                        <a href="#" class="text-white"><i class="icon-cog3"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /user menu -->

        
        <!-- Main navigation -->
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <!-- Main -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
                <li class="nav-item">
                    <a href="index.html" class="nav-link active">
                        <i class="icon-home4"></i>
                        <span>
                            Dashboard
                            <span class="d-block font-weight-normal opacity-50">No active orders</span>
                        </span>
                    </a>
                </li>
            
                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link"><i class="icon-city"></i> <span>Vertical navigation</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Vertical navigation">
                        <li class="nav-item"><a href="navigation_vertical_collapsible.html" class="nav-link">Collapsible menu</a></li>
                       <li class="nav-item"><a href="navigation_vertical_disabled.html" class="nav-link">Disabled items</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="../../../RTL/default/full/index.html" class="nav-link"><i class="icon-width"></i> <span>RTL version</span></a></li>
                <!-- /main -->

                <!-- Layout -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Users</div> <i class="icon-menu" title="Layout options"></i></li>
           
                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link"><i class="icon-users4"></i> <span>User Management</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="User Management">
                         <li class="nav-item"><a href="{{route('users.index')}}" class="nav-link"><i class="icon-user" title="Layout options"></i>View Users</a></li>
                        <li class="nav-item"><a href="{{route('users.create')}}" class="nav-link"><i class="icon-user-plus" title="Layout options"></i>Add Users</a></li>
                    </ul>
                </li>
                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link"><i class="icon-key"></i> <span>   Role Management</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Role Management">
                         <li class="nav-item"><a href="{{route('roles.index')}}" class="nav-link">View Roles</a></li>
                        <li class="nav-item"><a href="{{route('roles.create')}}" class="nav-link">Add New Role</a></li>
                    </ul>
                </li>
              
           
                <!-- /layout -->
                    
            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->
    
</div>