routes/web.php
<?php

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/app', function () {
    return view('Layout.index');
})->middleware('auth')->name('dashboard');
Route::get('/test', function () {
    return view('test.index');
});

Route::post('/login',[\App\Http\Controllers\LoginController::class, 'login'])->name('login');

Route::get('/logout',[\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

Route::resource('users', UserController::class);
Route::resource('roles', RoleController::class);

Route::get('/login', function () {
    return view('login');
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();

        return view('role.index',['roles' => $roles]);
        #return view('role.create', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "role" => "required",
        ]);
        $role = Role::create(['name' => $request->role]);
        return "role has been created";
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/role/index.blade.php
@extends('Layout.index')

@section('content')

<div class="card">

    <div class="card-header header-elements-inline">
        <h5 class="card-title">Basic initialization</h5>
        <div class="header-elements">
          <!--
  <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>
            </div>

          -->
        </div>
    </div>

    <div class="card-body">
        The HTML5 export buttons plug-in for Buttons provides four export buttons: <code>copyHtml5</code> - copy to clipboard; <code>csvHtml5</code> - save to CSV file; <code>excelHtml5</code> - save to XLSX file (requires JSZip); <code>pdfHtml5</code> - save to PDF file (requires PDFMake). This example demonstrates these four button types with their default options. Please note that these button types may also use a Flash fallback for older browsers (IE9-).
    </div>		  
     <form action="{{ route('roles.store') }}" method="POST">
        @csrf
    @method('post')			
    <div class="col-lg-10">
        <div class="input-group">
            <input type="text" class="form-control border-right-0" placeholder="Teal button" name="role"> 
            <span class="input-group-append">
                <button class="btn bg-teal" type="button">save role</button>
            </span>
        </div>
    </div>
</form>
    {{$roles}}
</div>




@endsection